### DISCUSSION TITLE
Should the Categorical Variant class include expressions?

### DISCUSSION THREAD

**Discussion by brendanreardon** [ga4gh/cat-vrs#124] [Q&A]
VRS 2.0 added a new data class called [_Expression_](https://vrs.ga4gh.org/en/2.x/concepts/AdditionalDataTypes/index.html#expression), that is included as the field `expression` within the [_Variation_](https://vrs.ga4gh.org/en/2.x/concepts/AdditionalDataTypes/index.html#variation) data class. This field is for representing variants in other syntaxes, including HGVS and SPDI.

Having a dedicated place for HGVS representations was a [request from the November trial use ballot](https://github.com/ga4gh/cat-vrs/discussions/86#discussioncomment-11479004) and, currently, HGVS representations are captured within `extensions`. For example, from [examples/proteinSequenceConsequence-ex1.yaml](https://github.com/ga4gh/cat-vrs/blob/ddafbd2ebd9f30110a9a44c496cc3716dd5f1d90/examples/proteinSequenceConsequence-ex1.yaml#L44-L72):
```
extensions:  
- name: hgvs list
    value:
      - nucleotideExpression:
          syntax: hgvs.g
          value: NC_000007.13:g.55259515T>G
        nucleotideType: genomic
      - nucleotideExpression:
          syntax: hgvs.c
          value: NM_005228.5:c.2573T>G
        nucleotideType: coding
      - nucleotideExpression:
          syntax: hgvs.c
          value: ENST00000275493.2:c.2573T>G
        nucleotideType: coding
      - nucleotideExpression:
          syntax: hgvs.c
          value: ENST00000275493.7:c.2573T>G
        nucleotideType: coding
        maneSelect: true
        proteinExpression:
          syntax: hgvs.p
          value: NP_005219.2:p.Leu858Arg
        molecularConsequence:
          name: missense_variant
          system: http://www.sequenceontology.org/browser/
          systemVersion: release_2.5.3
          code: SO:0001583
          iris:
            - http://www.sequenceontology.org/browser/release_2.5.3/term/SO:0001583
```

This _may_ not be necessary, as any Sequence or Copy Number Variant should be able to be represented as a VRS Variation object. However, having the hgvs representation for data types not (yet?) covered by VRS 2.0, such as fusions and translocations, would be helpful.
