### DISCUSSION TITLE
New Constraint to handle fusion / Rearrangement / translocation variants

### DISCUSSION THREAD

**Discussion by DanielPuthawala** [ga4gh/cat-vrs#55] [General]
Discussion thread to host discussion on the development of a new constraint or constraints to handle Fusion variants, one of the largest and most clinically actionable (see Wagner lab manuscript in prep) variant categories left in [the Cat-VRS variant test set](https://docs.google.com/document/d/1aV-SqxdmuRN_EKvafzTSe0GoGC9yOzPsjrdWE0LXqYc/edit?usp=sharing).  Similar coverage is needed also to handle rearrangement and translocation variants.

One very basic outstanding question is whether we think we need a constraint specifically to handle fusions, or if fusion variants are 'simply' a constrainted subset of rearrangment variants.

I will mock up something in this space soon based on one or more of the fusion variants in the test set.  If you are an expert or know someone who is an expert on the fusions, I would love to get your input here or meet with you on a call so you can tell me everything we should know from a clinical perspective when modelling these concepts.

**Comment by brendanreardon** [comment]
Just adding some relevant papers and resources:
- [Bruford, E. A. et al. HUGO Gene Nomenclature Committee (HGNC) recommendations for the designation of gene fusions. Leukemia vol. 35 3040–3043 (2021)](https://www.nature.com/articles/s41375-021-01436-6)
- [Wagner, A. H. et al. Recommendations for future extensions to the HGNC gene fusion nomenclature. Leukemia vol. 35 3611–3612 (2021).](https://pmc.ncbi.nlm.nih.gov/articles/PMC8632684/)
- [HGVS general recommendations](https://hgvs-nomenclature.org/stable/recommendations/general/)
- [VICC gene fusion specification](https://fusions.cancervariants.org/en/latest/)

**Comment by DanielPuthawala** [comment]
Question:  in this figure here (from the 2021 HUGO paper), (large?) sequence deletions are counted as a type of unbalanced rearrangment in that two hitherto non-adjacent bits (the borders of the deletion) are now found adjacent to each other.  Are all deletions therefore commonly considered to be a subset of rearrangements?  Is this an equivalency that we need to make transparent in Cat-VRS?

![Screenshot 2024-12-30 at 10 31 49 AM](https://github.com/user-attachments/assets/c469fdfe-545f-4c08-b8a2-abaa3620a276)

**Reply by brendanreardon** [reply]
> Are all deletions therefore commonly considered to be a subset of rearrangements? Is this an equivalency that we need to make transparent in Cat-VRS?

I'm interpreting "all" as rearrangement deletions, copy number deletions, and (short) nucleotide deletions. From my understanding, this is _not_ true and thus is not an equivalency that we need to model. Instead I tend to think of it as a venn diagram with some overlap. The key distinction is probably scale, with a lot more overlap between rearrangement deletions and copy number deletions. 
- Rearrangement deletions are when the flanking regions are joined. These also tend to be large, involving huge portions of chromosomes. 
- Copy number deletions really are talking about if there is loss of genetic material at a given location, which can be focal (at scales like an exon or a few genes) or broad (generally refers to it being a large chunk of a chromosomal arm). These can happen with or without a rearrangement. 
- Nucleotide deletions tend to be just a small number of bases and impact just a single gene or region. With NGS we can really only detect "short" insertion or deletions, which tend to be on the scale of tens or low hundreds of bases. One of the reasons that people are excited about long-read sequencing is that it should help us detect longer insertions and deletions and small structural variants, which will help us identify events that blur the lines between these different categories. 

If it's...
- 1s - low 100s of bases: nucleotide deletion
- 100s - megabases: copy number deletion
- 1000s of bases or more: structural variant deletion

[This is a nice review](https://www.nature.com/articles/s41576-019-0171-x) on aneuploidy / the copy number side of things, in cancer.

**Comment by brendanreardon** [comment]
We began brainstorming this constraint as part of the GKS Think Tank: https://github.com/ga4gh/gks-portal/issues/51

**Comment by ahwagner** [comment]
`v` and `?` properties should be re-evaluated. I think that these nomenclature representations should not be stored as single-character const elements in the adjoined elements array.

**Reply by DanielPuthawala** [reply]
Oh, good point.  How do we feel about `multipleKnownGeneElement` and `unknownElement`, respectively?

**Reply by brendanreardon** [reply]
This was (potentially) resolved [in the Pull Request with changes described here](https://github.com/ga4gh/cat-vrs/pull/178#issuecomment-3706214367). Retagged [Alex in the Pull Request, too](https://github.com/ga4gh/cat-vrs/pull/178#issuecomment-3711680746) to follow up about this requested change.

**Comment by DanielPuthawala** [comment]
Question raised by Bob Dolin: How to represent a fusion involving one known aprtner where the order is not known.

**Reply by DanielPuthawala** [reply]
Answer: We definitely meant to enable representation of those cases but that capability was lost at some point accidentally.  It was suggested that we handle this by flagging whether the `adjoinedElements` array is ordered or unordered.  So, eg, `[ALK, unknownElement], ordered = True` represents ALK::?, whereas `[ALK, unknownElement], ordered = False` merely represents a fusion involving ALK and an unknown partner without any knowledge as to wether ALK is the 5' or 3' partner.

**Comment by brendanreardon** [comment]
We've discussed a draft Adjacency Constraint at the [2026-01-07](https://docs.google.com/document/d/1oI4ir4OzXFvhZNbMVEX-RHGAQ-d2K4lAKP-7lf-uzPc/edit?tab=t.0#heading=h.jfgwszycgiyf) and [2026-01-20](https://docs.google.com/document/d/1oI4ir4OzXFvhZNbMVEX-RHGAQ-d2K4lAKP-7lf-uzPc/edit?tab=t.0#heading=h.84hgbw9xaacu) meetings and are currently left with two remaining design decisions to make. We would love feedback from our stakeholder implementers before merging [this Pull Request](https://github.com/ga4gh/cat-vrs/pull/178). The two decisions are:
- How should we model the concept of "Multiple Known Gene Components" from the VICC Fusion guidelines?
- Should this be a "Defining" Constraint?

The current version of the drafted readthedocs for the Adjacency Constraint and Gene Fusion Recipe can be found [here](https://github.com/ga4gh/cat-vrs/pull/178#issuecomment-3764112721). Slides used as conversation aids used during the [2026-01-07](https://docs.google.com/document/d/1oI4ir4OzXFvhZNbMVEX-RHGAQ-d2K4lAKP-7lf-uzPc/edit?tab=t.0#heading=h.jfgwszycgiyf) and [2026-01-20](https://docs.google.com/document/d/1oI4ir4OzXFvhZNbMVEX-RHGAQ-d2K4lAKP-7lf-uzPc/edit?tab=t.0#heading=h.84hgbw9xaacu) meetings can also be found [here](https://docs.google.com/presentation/d/1NKez9MJKXEDlx0nw7A8CtEjf_4kvdaXmadreDtNAXE4/edit?usp=sharing). 

I am going to make a separate comment for each of these design decisions, so that conversation for each can be contained within the respective comment replies.

**Comment by brendanreardon** [comment]
## How should we model the concept of Multiple Known Gene Components?
The VICC Gene Fusion guidelines has a described element as [Multiple Possible Gene Components](https://fusions.cancervariants.org/en/latest/nomenclature.html#multiple-possible-gene-component) for [Categorical Gene Fusions](https://fusions.cancervariants.org/en/latest/terminology.html#categorical-fusions). This concept exists to represent an adjoining element that is undefined. For example, a knowledge base may use this to catalog "ALK fusions" as "v::_ALK_" where "v" could represent multiple other genes. 

The design decision is ultimately: **Do we want to include an array of potential elements in this object**? 

Some options for how to represent this include:
1. Define an object that is a constant value to communicate an unspecified partner. This would be [this object without the `knownElements`](https://github.com/ga4gh/cat-vrs/blob/9b1f938ef23756d88ee441b0242eb658fa8dccb6/schema/cat-vrs/cat-vrs-source.yaml#L275-L293) property.
2. Define an object that allows you to list a non-exhaustive array of potential knownElements. This was our third version and is currently represented using a Concept Set from GKS core. ([Link to comment with a picture of the Readthedocs](https://github.com/ga4gh/cat-vrs/pull/178#issuecomment-3706214367), [Link to schema](https://github.com/ga4gh/cat-vrs/blob/9b1f938ef23756d88ee441b0242eb658fa8dccb6/schema/cat-vrs/cat-vrs-source.yaml#L275-L293)). Including example knownElements was a suggestion raised at one of the Think Tank sessions. A primary concern raised at the 2026-01-20 meeting is that this array of knownElements may be changed over time, which changes the definition of the categorical variant. 
3. Define a general "Unknown Element" object that would be used to represent both [Unknown Gene Element](https://fusions.cancervariants.org/en/latest/nomenclature.html#unknown-gene-component)s and [Multiple Possible Gene Components](https://fusions.cancervariants.org/en/latest/nomenclature.html#unknown-gene-component). 

There was also discussion at the 2026-01-20 meeting about if this element should be scoped to "Gene" to align with the VICC Fusion guidelines, or should it be generalized to any location? Alignment with the VICC Fusion guidelines would then be described within accompanying Implementation Guidance documentation.

**Reply by DanielPuthawala** [reply]
A central tension in this discussion is the (perhaps unreconcilable) non-alignment between the VICC fusion guidelines treating the array of multiple known partners as being non-exhaustive (in certain contexts) versus the need for the spec to allow for unambiguous representation and allow for efficient implementation.

If the `MultipleKnownGeneElements` array is treated as being exhaustive, then yes, updating that list will change the catvar. That will require some matching logic for the constraint, but I personally think that's relatively manageable (e.g.  if we have an NTRK::[A, B] catvar and an NTRK::[A, B, C] catvar, it is reasonable to conclude that the latter is a subset if the former).

If the `MultipleKnownGeneElements` array is treated as being non-exhaustive (ie cases where the `NTRK` part really matters, and the precise identity of the partners doesn't really matter), then we don't compute the logical inference in the above example, but in addition, we lose the ability to do so at all, and in addition, we now have many different ways to represent the same catvar, since, among other things, NTRK::[A, B] and NTRK::[A, B, C] could represent the same thing, as does NTRK::[].  This also conflates with the case of NTRK::UnknownGeneElement.

The proposal that I think @larrybabb , Parijat, and I agreed on (and correct me if I'm misrepresenting you guys), is to (1) treat the conceptset array of `MultipleKnownGeneElements` as being an exhaustive list, and (2) to change the name to something that explicity does not resemble the term in the VICC fusion spec so as not to mislead people into thinking that it works differently than it does.

As a corollary to this, I am in favor of naming it something like `unspecifiedElement`.  I propose `unspecified` as opposed to `unknown` so as not to imply either that it is unspecified due to being unknown vs unnecessary to care about, and I propose `Element` over `GeneElement` as rearrangements (as a broader class than just fusions) can involve sub-or-non-gene partners, such as regulatory elements or specific gene domains, and so we don't want to imply that only genes are valid partners when they're not (that's what the fusion recipe would be for).

**Reply by ahwagner** [reply]
We should make this use-case driven. For the data relevant to the VICC driver project, we need the non-exhaustive list, aligned with the VICC fusion specification. If there are other community use cases where there is the "exhaustive list" concept, I may have missed those; can they be documented here?

In the last Cat-VRS call I attended there was comment about how the list of known partners in a multi-gene element is an annotation, and therefore not relevant to interpretation or efficient computational representation. I disagree with this perspective, as using a multigene element in a fusion structure: (A) reaffirms this as a chimeric transcript gene fusion with a known partner, and (B) provides a basis on which other putative partners may be compared for structural or functional (dis)similarity.

**Reply by brendanreardon** [reply]
Thank you, @DanielPuthawala! We will have to wait for Beth, Bob, and Wes to weigh in but you three have convinced me to generalize the name of the object to be "unspecifiedElement". We can describe in implementation guidance of what this may look like for a VICC-aligned Gene Fusion use case.

@ahwagner Thank you for the thorough response. The one other concern raised from the group on Tuesday's call is that the list of known partners may change over time due to being a mutable array, which would change the definition of the defined categorical variant. Does that concern change your perspective whatsoever? Personally, I think that this would be okay because Cat-VRS is not generating a hash for implemented Constraints.

**Reply by brendanreardon** [reply]
@DanielPuthawala shared comments from @wesleygoar 
> I just talked to Wes and he went through a list of examples that they care clinically about, and he's fine with renaming unknownGeneElement to unspecifiedElement, particularly since they often care about exon-level or domain-level features, as well as treating the conceptset as being an exhaustive list of known fusion partners at the time the catvar was minted, since the cases where they treated it as being non-exhaustive they didn't care what the partners are anyway, and when they DO care what the partners are, knowing that something is NOT on the list is important.

**Reply by rhdolin** [reply]
My main issue was "what do we mean by **constraint**". @larrybabb had made a comment at the same call I was on, something about his desire for clear computing rules when testing an assayed variant against a categorical variant. I was a bit concerned that adding a non-exhaustive (and potentially changeable) set as a **constraint** will hamper this objective.

**Reply by bpitel12** [reply]
> @DanielPuthawala shared comments from @wesleygoar
> 
> > I just talked to Wes and he went through a list of examples that they care clinically about, and he's fine with renaming unknownGeneElement to unspecifiedElement, particularly since they often care about exon-level or domain-level features, as well as treating the conceptset as being an exhaustive list of known fusion partners at the time the catvar was minted, since the cases where they treated it as being non-exhaustive they didn't care what the partners are anyway, and when they DO care what the partners are, knowing that something is NOT on the list is important.

I agree with this. Often, fusions are interpreted by the features (domains/exons/etc) maintained by the primary fusion partner. Sometimes you care about whether the partner gene has a DNA binding domain or something similar and sometimes you dont. I'm fine with unspecifiedElement.

**Reply by bpitel12** [reply]
From a practical standpoint, I agree with Wes' reported comments about caring about exon-level and/or domain-level features. "unspecifiedElement" works for me.  I would encourage multiple examples in any reference material since the language isn't super intuitive to a dangerous novice like me.

**Reply by brendanreardon** [reply]
To summarize, 
- There needs to be a place to non-exhaustively list potential fusion partners, and this is needed to support VICC's use case. Including this list of potential fusion partners aids categorical variant matching in the VICC use case. 
- There is a concern about treating the ConceptSet as a non-exhaustive list of potential partners, especially if this set gets changed over time because it may impact categorical variant matching. 

As far as I see it, the paths forward for managing how to represent the Multiple Known Gene Components are:
- Use as a concept set, state it as non-exhaustive, and that may be altered in the future (worry about modifications impact categorical variant matching)
- Use as a concept set, state it as exhaustive at the time of categorical variant minting, and it is up to the implementer to not alter it over time
- Revert to a separate data class for Multiple Possible Gene Elements that is _not_ a Concept Set, and include examples of potential partners within extensions for the Categorical Variant object. Whether these examples are exhaustive or non-exhaustive would be up to the specific implementer. 

What did I miss? Was anything in this summary unfair?

**Reply by ahwagner** [reply]
I think that's a pretty good summary, thanks @brendanreardon. However, I do want to clarify a few things. Apologies for length of the response, and hoping we can pick this up during tomorrow's call.

1. IMO, we should nail down the use cases first (do the Driver Projects and other registered implementations capture and need to share known associated genes for fusions? do they capture and need to share known exon- and domain-level features?), the information model second (when providing a list of known gene partners, are these _definitional_, or _supporting_ properties?), and the data model last (should we use a _concept set_ object to represent these?). It is hard to answer all of these questions simultaneously and it can burden the decision process.
2. Putting aside concerns about the actual data we are trying to model, I'm not 100% sure I understand the comments being made by @DanielPuthawala about the importance / unimportance of gene fusion partners. Yes, functional domains are important and people definitely care about these clinically; indeed, functional domains are a [core part of the VICC fusion information model](https://fusions.cancervariants.org/en/latest/information_model.html#functional-domains), which was developed by consensus across a broad clinical community (including members of the NCH clinical team). That same model _also_ supports specifying known partners when known, and I'm not sure why one precludes the other. This statement:
> since the cases where they treated it as being non-exhaustive they didn't care what the partners are anyway

might be at the heart of the disconnect. I am not convinced that this represents a broad or consensus opinion, or is as absolute as it is being presented here. More likely there is a disconnect somewhere in the communication chain here, as the ongoing VICC Gene Fusion Oncogenicity effort (which also involves a diverse collective of community experts) also explicitly uses knowledge of known partners as criteria supporting oncogenicity in a novel gene fusion; that seems incongruous with "they didn't care what the partners are anyway".

3. Coming back to the data we are trying to model, certainly VICC resources such as OncoKB and CIViC describe known partners for fusions in summaries of fusion classes with multiple known partners driving oncogenicity. For example, the [ALK Fusions variant in OncoKB](https://www.oncokb.org/gene/ALK/somatic/Fusions) explicitly indicates EML4::ALK and NPM::ALK as notable known oncogenic fusions; [CIViC similarly notes EML4](https://civicdb.org/molecular-profiles/495/summary) in their v::ALK record. If we choose not to support capture of these data in the definition of the variant class (which seems like the obvious place given the source data available), then we would need to support this elsewhere.

**Reply by brendanreardon** [reply]
Thank you, Alex!

> IMO, we should nail down the use cases first (do the Driver Projects and other registered implementations capture and need to share known associated genes for fusions? do they capture and need to share known exon- and domain-level features?), the information model second (when providing a list of known gene partners, are these definitional, or supporting properties?), and the data model last (should we use a concept set object to represent these?). It is hard to answer all of these questions simultaneously and it can burden the decision process.

Just adding that I appreciate this comment. I'll separately ping our driver projects for this feature, but my hunch is:
- Functional domains and specific exons are _definitional_ to the adjacency when specified (e.g., if some domains need to be preserved or lost).
- Known gene fusion partners are _supporting_, at least for the champion implementations for this feature. The definition of the categorical variant will be relative to an unspecifiedElement, and the known gene fusion partners would be supplementary information. 
- Separately, exon and domain features are also relevant for representing assayed fusions. Ultimately assayed fusions would be represented using VRS Adjacencies with sequence locations, and optionally listed as a `member` under any categorical gene fusion.

**Reply by brendanreardon** [reply]
Here is a modified version of what a Gene Fusion may look like with an UnspecifiedElement as one partner, and the Known Gene Elements listed as an extension:
```yaml
id: civic.fid:62026
type: CategoricalVariant
name: v::NTRK1(hgnc:8031)
description: >-
  An optional field to describe v::NTRK1(hgnc:8031).
aliases:
  - v::NTRK1
  - NTRK1 fusion
constraints:
  - type: AdjacencyConstraint
    orderKnown: false
    adjoinedElements:
      - type: UnspecifiedElement
      - id: hgnc:8031
        conceptType: Gene
        name: NTRK1
        primaryCoding:
          id: hgnc:8031
          name: NTRK1
          system: https://genenames.org
          code: HGNC:8031
          iris:
            - https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:7230
extensions:
  - name: Known Gene Elements
    description: Known gene elements that may satisfy this Categorical Variant. Please specify if this array is exhaustive or non-exhaustive, and if it is subject to change.
    value: 
      type: ConceptSet
      membershipOperator: OR
      concepts:
        - id: hgnc:6636
          conceptType: Gene
          name: LMNA
          primaryCoding:
            id: hgnc:6636
            name: LMNA
            system: https://genenames.org
            code: HGNC:6636
            iris:
              - https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:6636
        - id: hgnc:11758
          conceptType: Gene
          name: TFG
          primaryCoding:
            id: hgnc:11758
            name: TFG
            system: https://genenames.org
            code: HGNC:11758
            iris:
              - https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:11758
        - id: hgnc:11998
          conceptType: Gene
          name: TP53
          primaryCoding:
            id: hgnc:11998
            name: TP53
            system: https://genenames.org
            code: HGNC:11998
            iris:
              - https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:11998
        - id: hgnc:12012
          conceptType: Gene
          name: TPM3
          primaryCoding:
            id: hgnc:12012
            name: TPM3
            system: https://genenames.org
            code: HGNC:12012
            iris:
              - https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:12012
        - id: hgnc:12017
          conceptType: Gene
          name: TPR
          primaryCoding:
            id: hgnc:12017
            name: TPR
            system: https://genenames.org
            code: HGNC:12017
            iris:
              - https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:12017
```
