### DISCUSSION TITLE
Add `subType` or something to computationally indicate type of variant

### DISCUSSION THREAD

**Discussion by larrybabb** [ga4gh/cat-vrs#81] [Ideas]
As we are dealing with getting VA-spec to Trial Use 1.0.0 we are finding that we need some of the basic CategoricalVariant classes to be in Trial Use as well. We also have hit the following point of discussion which needs to be hashed out with the Cat-VRS folks.

In the va-spec/tests/fixtures (1.x branch) folder there are several test yaml files for various va-spec statement, evidenceline and studyresult types.  The `AVE-clinical-classification.yaml` in particular has the following comment in it at this time

```
type: EvidenceLine
targetProposition:
  type: VariantPathogenicityProposition
  subjectVariant:
    # LB: Alex, please verify the following... I am using a Cat-VRS: ProteinSequenceConsequence
    #     I want to review this because there's nothing in this object to tell you that
    #     It looks identical to the CanonicalAllele except for the data constraints on
    #     which relations are allowed. 
    #     I think it makes sense for some Recipes to have a more specific object type or subtype property
    #     maybe something like recipeType: ProteinSequenceConsequence? (recipe is a bit non-computational computationally speaking)
    #       categoryType or categorySubtype seems better - the focus is on the category portion of CategoricalVariant.
    #     
    #     I recognize that computational validation will work fine without this
    #     but I would imagine it may make debugging validation failures much easier
    #     if the categoryType or recipeType was stated explicitly in the object.
    type: CategoricalVariant
    # subtype: ProteinSequenceConsequence  or categoryType: ProteinSequenceConsequence
    constraints:
      - type: DefiningAlleleConstraint
        allele:
          id: ga4gh:VA.t0rDoiIessOWmP0SF0plhXtOwi8TRaZz
          type: Allele
          location:
            type: SequenceLocation
            sequenceReference:
              refgetAccession: SQ.w7LxW0PSaVPNsPFvOL24weFjHcfaHyOi
              type: SequenceReference
            start: 10
            end: 11
            sequence: R
          state:
            type: LiteralSequenceExpression
            sequence: T
          expressions:
            - syntax: hgvs.p
              value: NP_000305.3:p.Arg11Thr
        relations:
          - translates_from
          - translates_from_reading_frame
  predicate: isCausalFor
  objectCondition:
    conceptType: Condition
    label: Unspecified
  geneContextQualifier:
    conceptType: Gene
    label: PTEN
... goes on...
```

I am in favor of adding a `categoryType` field that allows us to specify the particular type of categorical variant that is being represented, since we no longer put that in the `type` field based on how we are using `constraints` instead of subclassing `CategoricalVariant`.

I think this information if quite important to the downstream computational consumer (and human consumer) in that you do not have to discern the type of variant from the mixture of constraints.
