### ISSUE TITLE
Tests aren't running on every example

### ISSUE THREAD

**Issue by jsstevenson** [ga4gh/cat-vrs#154]
https://github.com/ga4gh/cat-vrs/blob/1.0/tests/test_definitions.yaml is missing some recently-added examples. This means that the test suite/CQA github action isn't running any validation on them.

I'm just eyeballing, but I think there's at least 1 error in those examples that would fail validation if they were included in the test suite.

**Comment by brendanreardon** [comment]
Whoops thank you for catching this, James! I'll get on this.

**Comment by brendanreardon** [comment]
Oof @DanielPuthawala, we should probably chat about this and then summarize here. In short, neither categoricalCnv-ex4.yaml (tp53 copy loss) nor braf-v600.yaml are currently included in the test_definitions.yaml. I don't remember if this was intentionally or not for the subsequent reasons, either way -- this was an oversight and is on me. 

For explicit errors, the featureContextConstraint within example categoricalCnv-ex4.yaml accidentally had the primaryCoding set as an array. [This is now fixed in branch 154-patch-pytext-examples](https://github.com/ga4gh/cat-vrs/compare/1.0...154-patch-pytest-examples).

Neither examples were included in the tests because the test suite test relative to defined Recipes, and neither satisfy current Recipes.

[categoricalCnv-ex4.yaml](https://github.com/ga4gh/cat-vrs/blob/47781cc1c0d37521c8336367b56355f274977b75/examples/categoricalCnv-ex4.yaml) does not satisfy the CategoricalCNV recipe because we only set a FeatureContextConstraint and CopyChangeConstraint, and CategoricalCNV requires a DefiningLocationConstraint and either a CopyChangeConstraint or CopyCountConstraint. Furthermore, categorical variants satisfying this Recipe can _only_ have these constraints due to the [`maxItems` value set on the constraints array](https://github.com/ga4gh/cat-vrs/blob/47781cc1c0d37521c8336367b56355f274977b75/schema/cat-vrs/recipes-source.yaml#L89). We discussed the `maxItems` property a bit when originally implementing [FeatureContextConstraint](https://github.com/ga4gh/cat-vrs/issues/98) but we didn't circle back about it.

I also added a DefiningLocationConstraint corresponding to _TP53_'s location [according to RefSeq](https://www.ncbi.nlm.nih.gov/gene/7157), but it will still fail validation due to FeatureContextConstraint being included. [We'll have to resolve how we want to handle FeatureContextConstraint](https://github.com/ga4gh/cat-vrs/discussions/117) before resolving these examples being validated and this Issue, I think. Specifically if feature context should be "nested" within DefiningAllele and/or DefiningLocationConstraint, or if we are okay with "redundant" information being shared at the constraint level.

As for [braf-v600.yaml](https://github.com/ga4gh/cat-vrs/blob/47781cc1c0d37521c8336367b56355f274977b75/examples/braf-v600.yaml), I think that we need to either mint a new Recipe or expand the test suite to evaluate examples independent of Recipes. At the moment a Recipe needs to be specified with the "definition" property for [validation tests to be run on an example](https://github.com/ga4gh/cat-vrs/blob/1.0/tests/test_definitions.yaml).

Thank you again, @jsstevenson!

**Comment by DanielPuthawala** [comment]
Yes, sure, let's chat about it.

Re: `categoricalCnv-ex4.yaml` not satisfying the `CategoricalCNV` recipe, that's fine and makes sense.  The fact that the `maxItems` is behaving that way is 100% not what was intended, so we definitely need to straighten that bug out.

As for the TP53 Loss example itself, yea, I agree that we should get the `FeaturecontextConstraint` straightened out first, and the circle back around to it.  More importantly, (and as you alluded to in the last bit) we need to be able to validate any catvar whether it satisfies any recipes or not, because they are under no obligation to. (or we could create a maximally vague catvar recipe, like `DescribedVariation` or something that should validate everything) Do the tests currently predicate validation testing on the recipes that we have?

**Comment by brendanreardon** [comment]
`maxItems` for the constraints property was removed from CategoricalCNV, and [now all categoricalCnv examples are included in the tests](https://github.com/ga4gh/cat-vrs/commit/76d901cfef428edc7a349106410bd68632380e0c). The readthedocs [were also updated to say "at least" instead of "at most" for Recipes](https://github.com/ga4gh/cat-vrs/commit/26d0dc2b8ff8592508fbcf3f64dde8892ac9726b#diff-9319b33ce1d83e2ddc6e46666025d1bcb5bbbc670327c67fec43f68b6eff5628).

I additionally [resolved errors with the BRAF V600 example](https://github.com/ga4gh/cat-vrs/commit/37ce7d5d758343010927d013fb0cb249d6c1f611). 

> Do the tests currently predicate validation testing on the recipes that we have?

At the moment they do. I created Recipe for a DescribedVariant that essentially is a base CategoricalVariant, which can be used to validate any CategoricalVariant object. With that said, I don't _love_ calling this DescribedVariant. What do you think about calling it CategoricalVariantObject or CategoricalVariantInstance? It may also be worthwhile restructuring the recipes-source to have this as a base class, which other Recipes inherit from. 

Here is what it currently looks like:

```
$defs:
  DescribedVariant:
    maturity: draft
    description: >- 
      A Categorical Variant object that may or may not be represented with constraints. This Recipe is used to validate 
      instances of the :ref:`CategoricalVariant` class, regardless of Recipes being satisfied. Implementers may choose 
      to represent Categorical Variants *without* any constraints while waiting for this specification to support a 
      means to model them.
    allOf:
      - $ref: CategoricalVariant
      - properties:
          constraints:
            contains:
              anyOf:
                - $ref: CopyChangeConstraint
                - $ref: CopyCountConstraint
                - $ref: DefiningAlleleConstraint
                - $ref: DefiningLocationConstraint
                - $ref: FeatureContextConstraint
```

I likewise updated documentation for this Recipe, but I don't love either the description that I used for the Recipe (appears under Computational Definition in readthedocs) or the Information Model text. Any suggestions?

<img width="719" alt="Image" src="https://github.com/user-attachments/assets/ce32ea22-4b5b-471e-9fa4-f84964f487b0" />

Again, thank you for catching this @jsstevenson 😅
